### ISSUE TITLE
Voice is not recorded

### ISSUE THREAD

**Issue by vinodclix** [mdn/web-dictaphone#16]
I am trying to record voice using earphone or headphone but it is not working. Also it is working only on Firefox browser.

Recording is working if any music playing in the system.

**Comment by chrisdavidmills** [comment]
From my tests, this demo works on Firefox and Chrome desktop, but not on Safari desktop or any mobile browsers (`navigator.mediaDevices` doesn't seem to be working in any of those).

Does that match your experience?

**Comment by pkasson** [comment]
does not record in Safari - have javascript error - cant find:      const mediaRecorder = new MediaRecorder(stream);

**Comment by wfahle** [comment]
As of now, iOS 14.7.1, this still does not record audio. It is able to visualize the audio track now, and MediaRecorder interface exists, but the recorded clip simply says 'Error'. Drilling into the audio chunk, it looks like MP4.

**Comment by schalkneethling** [comment]
Hey @vinodclix! Thank you for opening this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please open a new issue if you still feel that this issue is relevant. Thank you.
