### ISSUE TITLE
Error using Iphone (iOS)

### ISSUE THREAD

**Issue by Resurgemuss** [mdn/web-dictaphone#25]
Hi everyone, thank you very much for creating this great app.

I have no issues using it in Chrome or Firefox when they are in Android or Windows, but in iPhone, recordings give an Error,  in both Chrome and Safari. 

So it seems as if it's a problem related to iOS instead of a browser problem.

I wonder if you know about it and if by chance you know how to solve it.

Thank you very much,

Best,

Carlos

**Comment by Resurgemuss** [comment]
I have just read another user comment in which it confirms that there is an issue with iOS 14.7.1 playing audio recorded, what a shame.

Best,

Carlos

**Comment by ken-hudd** [comment]
in the app.js line 80 change it to be:
const blob = new Blob(chunks, { 'type' : 'audio/mp4; codecs=aac' });

it will work on ios, at least every other recording...

**Comment by schalkneethling** [comment]
Hey @Resurgemuss! Thank you for opening this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please open a new issue if you still feel that this issue is relevant. Thank you.

@ken-hudd Once we have moved the repo, please do open a pull request to address this issue if you have confirmed that your suggestion in https://github.com/mdn/web-dictaphone/issues/25#issuecomment-938793678 resolves the issue. Thank you.
