### ISSUE TITLE
If you press 'Cancel' on the dialog to set clip name after recording clip, it... saves the clip anyway?

### ISSUE THREAD

**Issue by sole** [mdn/web-dictaphone#5]
This behaviour is confusing.

Perhaps it should pre-fill the answer and let you edit it if you wanted to.

**Comment by chrisdavidmills** [comment]
Heh, I probably shouldn't have used prompt()! It is really crappy, and there is no way to control the behaviour if the user clicks cancel. I added a default value to make it slightly less confusing, but when cancel is chosen it just returns null — really silly. I added a check for this so that if null is returned, it still fills in the name as the default value.

I also added a handler so that when you click on the clip name, you can rename it.
